version: '3.4'
services:
  bitcoind:
    image: kylemanna/bitcoind
    volumes:
      - ./bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf

  etcd-alice-1:
    restart: unless-stopped
    image: 'bitnami/etcd:3.5.0'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd-alice-1
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-alice-1:2379
      - ETCD_MAX_TXN_OPS=16384
      - ETCD_MAX_REQUEST_BYTES=104857600
      - ETCD_LOG_LEVEL=error
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-alice-1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-alice
      - ETCD_INITIAL_CLUSTER=etcd-alice-1=http://etcd-alice-1:2380,etcd-alice-2=http://etcd-alice-2:2380,etcd-alice-3=http://etcd-alice-3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new

  etcd-alice-2:
    restart: unless-stopped
    image: 'bitnami/etcd:3.5.0'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd-alice-2
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-alice-2:2379
      - ETCD_MAX_TXN_OPS=16384
      - ETCD_MAX_REQUEST_BYTES=104857600
      - ETCD_LOG_LEVEL=error
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-alice-2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-alice
      - ETCD_INITIAL_CLUSTER=etcd-alice-1=http://etcd-alice-1:2380,etcd-alice-2=http://etcd-alice-2:2380,etcd-alice-3=http://etcd-alice-3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new

  etcd-alice-3:
    restart: unless-stopped
    image: 'bitnami/etcd:3.5.0'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd-alice-3
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-alice-3:2379
      - ETCD_MAX_TXN_OPS=16384
      - ETCD_MAX_REQUEST_BYTES=104857600
      - ETCD_LOG_LEVEL=error
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-alice-3:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-alice
      - ETCD_INITIAL_CLUSTER=etcd-alice-1=http://etcd-alice-1:2380,etcd-alice-2=http://etcd-alice-2:2380,etcd-alice-3=http://etcd-alice-3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new

  etcd-bob-1:
    restart: unless-stopped
    image: 'bitnami/etcd:3.5.0'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd-bob-1
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-bob-1:2379
      - ETCD_MAX_TXN_OPS=16384
      - ETCD_MAX_REQUEST_BYTES=104857600
      - ETCD_LOG_LEVEL=error
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-bob-1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-bob
      - ETCD_INITIAL_CLUSTER=etcd-bob-1=http://etcd-bob-1:2380,etcd-bob-2=http://etcd-bob-2:2380,etcd-bob-3=http://etcd-bob-3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new

  etcd-bob-2:
    restart: unless-stopped
    image: 'bitnami/etcd:3.5.0'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd-bob-2
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-bob-2:2379
      - ETCD_MAX_TXN_OPS=16384
      - ETCD_MAX_REQUEST_BYTES=104857600
      - ETCD_LOG_LEVEL=error
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-bob-2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-bob
      - ETCD_INITIAL_CLUSTER=etcd-bob-1=http://etcd-bob-1:2380,etcd-bob-2=http://etcd-bob-2:2380,etcd-bob-3=http://etcd-bob-3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new

  etcd-bob-3:
    restart: unless-stopped
    image: 'bitnami/etcd:3.5.0'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd-bob-3
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-bob-3:2379
      - ETCD_MAX_TXN_OPS=16384
      - ETCD_MAX_REQUEST_BYTES=104857600
      - ETCD_LOG_LEVEL=error
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-bob-3:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-bob
      - ETCD_INITIAL_CLUSTER=etcd-bob-1=http://etcd-bob-1:2380,etcd-bob-2=http://etcd-bob-2:2380,etcd-bob-3=http://etcd-bob-3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new

  lnd-alice:
    restart: unless-stopped
    build: 
      context: lnd
      args:
        repo: http://github.com/lightningnetwork/lnd
        checkout: master
        tags: signrpc walletrpc chainrpc invoicesrpc monitoring kvdb_etcd
    depends_on:
      - bitcoind
      - etcd-alice-1
      - etcd-alice-2
      - etcd-alice-3
    volumes:
      - ./lnd.conf:/root/.lnd/lnd.conf
      - lnd-alice:/cfg
    ports:
      - 5000:5000      
    command: --tlsextradomain=lnd-alice --db.backend=etcd --db.etcd.host=etcd-alice-1:2379 --db.etcd.disabletls

  lnd-bob:
    restart: unless-stopped
    build: 
      context: lnd
      args:
        repo: http://github.com/lightningnetwork/lnd
        checkout: master
        tags: signrpc walletrpc chainrpc invoicesrpc monitoring kvdb_etcd
    depends_on:
      - bitcoind
      - etcd-bob-1
      - etcd-bob-2
      - etcd-bob-3
    volumes:
      - ./lnd.conf:/root/.lnd/lnd.conf
      - lnd-bob:/cfg
    ports:
      - 5001:5000      
    command: --tlsextradomain=lnd-bob --db.backend=etcd --db.etcd.host=etcd-bob-1:2379 --db.etcd.disabletls

  loadtest:
    build: loadtest
    depends_on:
      - lnd-alice
      - lnd-bob
    volumes:
      - lnd-alice:/lnd-alice
      - lnd-bob:/lnd-bob
      - ./${LOADTEST_CONFIG_FILE}:/loadtest.yml

volumes:
  lnd-alice:
  lnd-bob:
    
