version: '3.4'
services:
  bitcoind:
    image: kylemanna/bitcoind
    volumes:
      - ./bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf

  eclair-alice:
    restart: unless-stopped
    image: acinq/eclair:release-0.6.1.SNAPSHOT-sqlite-wal-mode
    depends_on:
      - bitcoind
    volumes:
      - ./eclair/eclair.conf:/data/eclair.conf
      - ./eclair/logback.xml:/data/logback.xml
    environment:
      JAVA_OPTS: -Dlogback.configurationFile=/data/logback.xml


  eclair-bob:
    restart: unless-stopped
    image: acinq/eclair:release-0.6.1.SNAPSHOT-sqlite-wal-mode
    depends_on:
      - bitcoind
    volumes:
      - ./eclair/eclair.conf:/data/eclair.conf
      - ./eclair/logback.xml:/data/logback.xml
    environment:
      JAVA_OPTS: -Dlogback.configurationFile=/data/logback.xml

  loadtest:
     build: loadtest
     volumes:
       - ./${LOADTEST_CONFIG_FILE}:/loadtest.yml
