version: '3.4'
services:
  bitcoind:
    image: kylemanna/bitcoind
    volumes:
      - ./bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf

  etcd-alice:
    restart: unless-stopped
    image: 'bitnami/etcd:3.4.16'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_MAX_TXN_OPS=16384
      - ETCD_MAX_REQUEST_BYTES=104857600

  etcd-bob:
    restart: unless-stopped
    image: 'bitnami/etcd:3.4.16'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_MAX_TXN_OPS=16384
      - ETCD_MAX_REQUEST_BYTES=104857600

  lnd-alice:
    restart: unless-stopped
    build: 
      context: lnd
      args:
        repo: https://github.com/bhandras/lnd
        checkout: 12e2fc025d8d100df9238fa7dd2a0ced32ecbddc
        tags: signrpc walletrpc chainrpc invoicesrpc monitoring kvdb_etcd
    depends_on:
      - bitcoind
      - etcd-alice
    volumes:
      - ./lnd.conf:/root/.lnd/lnd.conf
      - lnd-alice:/cfg
    ports:
      - 5000:5000      
    command: --tlsextradomain=lnd-alice --db.backend=etcd --db.etcd.host=etcd-alice:2379 --db.etcd.disabletls

  lnd-bob:
    restart: unless-stopped
    build: 
      context: lnd
      args:
        repo: https://github.com/bhandras/lnd
        checkout: 12e2fc025d8d100df9238fa7dd2a0ced32ecbddc
        tags: signrpc walletrpc chainrpc invoicesrpc monitoring kvdb_etcd
    depends_on:
      - bitcoind
      - etcd-bob
    volumes:
      - ./lnd.conf:/root/.lnd/lnd.conf
      - lnd-bob:/cfg
    ports:
      - 5001:5000      
    command: --tlsextradomain=lnd-bob --db.backend=etcd --db.etcd.host=etcd-bob:2379 --db.etcd.disabletls

  loadtest:
    build: loadtest
    depends_on:
      - lnd-alice
      - lnd-bob
    volumes:
      - lnd-alice:/lnd-alice
      - lnd-bob:/lnd-bob
      - ./${LOADTEST_CONFIG_FILE}:/loadtest.yml
 
volumes:
  lnd-alice:
  lnd-bob:
    
