version: '3.4'
services:
  lndsigner:
    build:
      dockerfile: Dockerfile.lndsigner
    ports:
      - 10021:10021
    volumes:
      - ./signer.conf:/root/.lndsigner/signer.conf
      - lndsigner:/cfg
    command: lndsignerd
    environment:
      - VAULT_ADDR=http://vault-server:8200
      - VAULT_TOKEN=hvs.uEtz6EKwavhojNrh8bEwdHOb

  vault-server:
    image: vault:latest
    ports:
      - "8200:8200"
    # cap_add:
    #   - IPC_LOCK
    command: server -log-level=trace # -config=/vault/config/config.hcl # -dev-plugin-dir=/vault/plugins
    volumes: 
      - ./vault_plugins:/vault/plugins
      - ./vault.hcl:/vault/config/config.hcl

  minio: 
    image: quay.io/minio/minio
    ports:
      - 19000:9000
      - 19090:9090
    environment:
      - MINIO_ROOT_USER=ROOTUSER
      - MINIO_ROOT_PASSWORD=CHANGEME123
  #  -v ${HOME}/minio/data:/data \
    command: server /data --console-address ":9090"
# Create vault-storage bucket via minio ui...

volumes:
  lndsigner:

networks:
  default:
    name: vault
